name: workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - tqdm
  - requests
  - nodejs
  - pip
  - pip:
    - bqplot
    - bokeh
    - matplotlib
    - ipywidgets
    - ipyleaflet
    - pandas
    - geopandas
    - osmnx
    - xlrd
    - qgrid